#ifndef __BROKER_DEFINE_H__
#define __BROKER_DEFINE_H__

#define IPC_BROKER	"IPC_BROKER"

enum {
	BROKER_EVENT_SYSTEM,
	BROKER_EVENT_NETWORK,
};

#define BROKER_EVENT_MASK_SYSTEM		(1ul << BROKER_EVENT_SYSTEM)
#define BROKER_EVENT_MASK_NETWORK		(1ul << BROKER_EVENT_NETWORK)


#define EVENTS_PER_MASK	1000


enum broker_event_system
{
	EVENT_MSG_SYSTEM_SLEEP			= EVENTS_PER_MASK * BROKER_EVENT_SYSTEM,
	EVENT_MSG_SYSTEM_WAKEUP,
	EVENT_MSG_SYSTEM_REBOOT,
	EVENT_MSG_SYSTEM_PWROFF,
};

enum broker_event_network
{
	EVENT_MSG_NETWORK_CONNECTING 		= EVENTS_PER_MASK * BROKER_EVENT_NETWORK,
	EVENT_MSG_NETWORK_CONNECTED,
	EVENT_MSG_NETWORK_DISCONNECTING,
	EVENT_MSG_NETWORK_DISCONNECTED,
};


#endif
